---
title: "Poro훾ilo projekta - galerija vseh grafov"
author: "An탑e Mramor"
date: "22 4 2022"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```


```{r vizualizacija, results='hide'}
source("~/Faks/mag 1 letnik/MzR/Time-to-yes-contract-and-money/vizualizacija/vizualizacija2.R", encoding="UTF-8")
```

## Analiza medsebojnih povezav podatkov, brez 훾asov

```{r graf1, echo=FALSE, fig.align='side', fig.show="hold", out.width="50%"}
graf1
graf1.1
graf1.2
graf1.3
graf1.4
```

```{r produkt po mesecih, echo=FALSE, fig.align='side', fig.show="hold", out.width="50%"}
prod.po.mes
prod.po.mes.2
```

```{r graf3, echo=FALSE, fig.align='side', fig.show="hold", out.width="50%"}
graf3
graf3.1
graf3.2
tip.po.mes
graf3.3
```

```{r graf4, echo=FALSE, fig.align='side', fig.show="hold", out.width="50%"}
graf4
graf4.1
graf4.2
graf4.3
```

```{r graf5, echo=FALSE, fig.align='side', fig.show="hold", out.width="50%"}
graf5
graf5.1
graf5.2
graf5.3
graf5.4
```

```{r graf6, echo=FALSE, fig.align='side', fig.show="hold", out.width="50%"}
graf6
graf6.1
graf6.3
graf6.3.2
graf6.4
graf6.4.2
```

```{r graf7, echo=FALSE, fig.align='side', fig.show="hold", out.width="50%"}
graf7.1
graf7.1.1
graf7.1.2
graf7.2
graf7.2.2
graf7.2.3
graf7.2.4
graf7.3
graf7.3.1
graf7.3.2
graf7.4
graf7.4.1
graf7.4.2
graf7.5
graf7.5.1
graf7.5.2
```

\newpage

## Analiza 훾asov v povezavi z ostalimi podatki
```{r graf16, echo=FALSE, fig.align='side', fig.show="hold", out.width="50%"}
graf16.1.1
graf16.1.2
graf16.1.3

graf16.2.1
graf16.2.2
graf16.2.3

graf16.3.1
graf16.3.2
graf16.3.3

graf16.4.1
graf16.4.2
graf16.4.3
```



```{r graf8, echo=FALSE, fig.align='side', fig.show="hold", out.width="50%"}
graf8.1
graf8.1.2
graf8.2
graf8.2.2
graf8.2.3
graf8.2.4
graf8.3
graf8.3.2
graf8.3.3
graf8.3.4
```

```{r casi.produkt, echo=FALSE, fig.align="center"}
casi.produkt.plt
casi.produkt.rac.plt
```


```{r graf9, echo=FALSE, fig.align='side', fig.show="hold", out.width="50%"}
graf9.1
graf9.1.2
graf9.2
graf9.2.2
graf9.2.3
graf9.2.4
graf9.3
graf9.3.2
graf9.2.4
graf9.3.4
```

```{r casi.mesec, echo=FALSE, fig.align="center"}
casi.mesec.plt
casi.mesec.rac.plt
```

```{r graf10, echo=FALSE, fig.align='side', fig.show="hold", out.width="50%"}
graf10.1
graf10.1.2
graf10.2
graf10.2.2
graf10.2.3
graf10.2.4
graf10.3
graf10.3.2
graf10.3.3
graf10.3.4
```

```{r casi.tipi, echo=FALSE, fig.align="center"}
casi.tip.plt
casi.tip.rac.plt
```

```{r graf11, echo=FALSE, fig.align='side', fig.show="hold", out.width="50%"}
graf11.1
graf11.1.2
graf11.2
graf11.2.2
graf11.2.3
graf11.2.4
graf11.3
graf11.3.2
graf11.3.3
graf11.3.4
```

```{r casi.regija, echo=FALSE, fig.align="center"}
casi.regija.plt
casi.regija.rac.plt
```

```{r graf12, echo=FALSE, fig.align='side', fig.show="hold", out.width="50%"}
graf12.1
graf12.1.2
graf12.2
graf12.2.2
graf12.2.3
graf12.2.4
graf12.3
graf12.3.2
graf12.3.3
graf12.3.4
```

```{r casi.poslovalnica, echo=FALSE, fig.align="center"}
casi.poslovalnica.plt
casi.poslovalnica.rac.plt
```


## Ne-prou-zelo uporabni grafi

poglej korelacije v napovedi.r


```{r graf13, echo=FALSE, fig.align='side', fig.show="hold", out.width="50%"}
graf13.1
graf13.2
graf13.2.2
graf13.3
graf13.3.2
graf15.1
```


```{r graf14, echo=FALSE, fig.align='side', fig.show="hold", out.width="50%"}
graf14.1
graf14.2
graf14.3
graf14.4
graf14.5
graf14.6
graf15.1
```